site_name: An Teanga Sean, Celtic Languages
theme_dir: theme
theme: null
copyright: 'Copyright &copy; 2017 <a href="mailto:jwhitehurst@mail.usf.edu">Joshua Whitehurst</a>'
repo_url: https://github.com/jwhitehurst37/an-teanga-sean
repo_name: 'GitHub'
pages:
- Home: 'index.md'
- Research Focus: 'research.md'
- Methodology: 'methodology.md'
- Data: 'data.md'
- Visual Analysis: 'visualizations.md'
- Conclusion & Works Cited: 'conclusion.md'
- Credits: 'credits.md'
